version: "3.8"

services:
  app:
    build: .
    image: whatsapp-mcm:latest
    container_name: whatsappmcm
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - BASIC_AUTH_REALM=${BASIC_AUTH_REALM}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
